<%@ Page Title="" Language="C#" MasterPageFile="~/WelcomePage.Master" AutoEventWireup="true" CodeBehind="AdminSite.aspx.cs" Inherits="JewellaryShopping.AdminSite" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="WelcomePage" runat="server">

    <asp:GridView ID="idView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" onrowdeleting="DeleteDetails" AutoGenerateEditButton="true" onrowupdating="UpdateDetails" onrowcancelingedit="CancelingEdit" onrowediting="Editing" DataKeyNames="UserId">
        <Columns>
            <asp:TemplateField HeaderText="UserId" runat="server">
                <ItemTemplate>
                    <asp:Label ID="UserLabel" runat="server" Text='<%# Bind("UserId") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Mail" runat="server">
                <EditItemTemplate>
                    <asp:TextBox ID="Mail" runat="server" Text='<%# Bind("MailId") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="MailLabel" runat="server" Text='<%# Bind("MailId") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Phone Number" runat="server">
                <EditItemTemplate>
                    <asp:TextBox ID="Phone" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="PhoneLabel" runat="server" Text='<%# Bind("PhoneNumber") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Role" runat="server">
                <EditItemTemplate>
                    <asp:TextBox ID="Role" runat="server" Text='<%# Bind("RoleOfMemeber") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="RoleLabe" runat="server" Text='<%# Bind("RoleOfMemeber") %>'></asp:Label>
                </ItemTemplate>
            </asp:TemplateField>

        </Columns>
    </asp:GridView>
</asp:Content>
