<%@ Page Title="" Language="C#" MasterPageFile="~/WelcomePage.Master" AutoEventWireup="true" CodeBehind="Product.aspx.cs" Inherits="JewellaryShopping.Product" %>
<asp:Content ID="Product" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="ProductSite" ContentPlaceHolderID="WelcomePage" runat="server">
    
    <asp:GridView ID="productView" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" onrowdeleting="DeleteDetails" AutoGenerateEditButton="true" onrowupdating="UpdateDetails" onrowcancelingedit="CancelingEdit" ShowFooter="true" onrowediting="Editing" DataKeyNames="ProductNumber">
        <Columns>
            <asp:TemplateField HeaderText="S.No">
                    <ItemTemplate>
                        <asp:Label ID="lblSerialNumber" Text='<%# Container.DataItemIndex + 1 %>' runat="server" />
                    </ItemTemplate>
                    <FooterTemplate>
                    <asp:LinkButton ID="Insert" Text="Insert" runat="server" OnClick="InsertProduct" />
                </FooterTemplate>
                </asp:TemplateField>
          <asp:TemplateField HeaderText="ProductNumber" runat="server">
               <EditItemTemplate>
                    <asp:TextBox ID="ProductNumber" runat="server" Text='<%# Bind("ProductNumber") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="NumberLabel" runat="server" Text='<%# Bind("ProductNumber") %>'></asp:Label>
                </ItemTemplate>
              <FooterTemplate>
                    <asp:TextBox ID="ProductNumber" Placeholder="Product Number" runat="server" />
                </FooterTemplate>
                
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Product" runat="server">
                <EditItemTemplate>
                    <asp:TextBox ID="Product" runat="server" Text='<%# Bind("productName") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="NameLabel" runat="server" Text='<%# Bind("productName") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="ProductName" Placeholder="Product Name" runat="server" />
                </FooterTemplate>
            </asp:TemplateField>
            <asp:TemplateField HeaderText="Rate" runat="server">
                <EditItemTemplate>
                    <asp:TextBox ID="Rate" runat="server" Text='<%# Bind("productRate") %>'></asp:TextBox>
                </EditItemTemplate>
                <ItemTemplate>
                    <asp:Label ID="RateLabel" runat="server" Text='<%# Bind("productRate") %>'></asp:Label>
                </ItemTemplate>
                <FooterTemplate>
                    <asp:TextBox ID="RateFooter" Placeholder="Product Rate" runat="server" />
                </FooterTemplate>
            </asp:TemplateField>
            
        </Columns>
    </asp:GridView>
</asp:Content>

